# Configuration Dependabot pour EventEase
# Conforme référentiel DWWM 2023

version: 2
updates:
  # Mise à jour des dépendances racine
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "EventEase Team"
    assignees:
      - "EventEase Team"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Mise à jour des dépendances client
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "EventEase Team"
    assignees:
      - "EventEase Team"
    commit-message:
      prefix: "chore(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
      - "automated"

  # Mise à jour des dépendances serveur
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "EventEase Team"
    assignees:
      - "EventEase Team"
    commit-message:
      prefix: "chore(server)"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
      - "automated"

  # Mise à jour des actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "EventEase Team"
    assignees:
      - "EventEase Team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "ci-cd"
      - "automated"
