# Workflow de test des secrets GitHub
# Conforme référentiel DWWM 2023

name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      test_deployment:
        description: 'Tester le déploiement'
        required: false
        default: false
        type: boolean

jobs:
  test-secrets:
    name: Test des Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      
    - name: Test Vercel Token
      run: |
        if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "✅ VERCEL_TOKEN configuré"
        else
          echo "❌ VERCEL_TOKEN manquant"
          exit 1
        fi
        
    - name: Test Vercel Org ID
      run: |
        if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
          echo "✅ VERCEL_ORG_ID configuré"
        else
          echo "❌ VERCEL_ORG_ID manquant"
          exit 1
        fi
        
    - name: Test Vercel Project ID
      run: |
        if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
          echo "✅ VERCEL_PROJECT_ID configuré"
        else
          echo "❌ VERCEL_PROJECT_ID manquant"
          exit 1
        fi
        
    - name: Test Railway Token
      run: |
        if [ -n "${{ secrets.RAILWAY_TOKEN }}" ]; then
          echo "✅ RAILWAY_TOKEN configuré"
        else
          echo "❌ RAILWAY_TOKEN manquant"
          exit 1
        fi
        
    - name: Test Snyk Token
      run: |
        if [ -n "${{ secrets.SNYK_TOKEN }}" ]; then
          echo "✅ SNYK_TOKEN configuré"
        else
          echo "⚠️ SNYK_TOKEN manquant (optionnel)"
        fi
        
    - name: Test Slack Webhook
      run: |
        if [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
          echo "✅ SLACK_WEBHOOK configuré"
        else
          echo "⚠️ SLACK_WEBHOOK manquant (optionnel)"
        fi
        
    - name: Résumé des secrets
      run: |
        echo "## 📋 Résumé de la configuration des secrets"
        echo ""
        echo "### ✅ Secrets requis configurés :"
        [ -n "${{ secrets.VERCEL_TOKEN }}" ] && echo "- VERCEL_TOKEN"
        [ -n "${{ secrets.VERCEL_ORG_ID }}" ] && echo "- VERCEL_ORG_ID"
        [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ] && echo "- VERCEL_PROJECT_ID"
        [ -n "${{ secrets.RAILWAY_TOKEN }}" ] && echo "- RAILWAY_TOKEN"
        echo ""
        echo "### ⚠️ Secrets optionnels :"
        [ -z "${{ secrets.SNYK_TOKEN }}" ] && echo "- SNYK_TOKEN (analyse de sécurité)"
        [ -z "${{ secrets.SLACK_WEBHOOK }}" ] && echo "- SLACK_WEBHOOK (notifications)"
        echo ""
        echo "### 🚀 Prêt pour le déploiement !"

  test-deployment:
    name: Test de Déploiement
    runs-on: ubuntu-latest
    needs: test-secrets
    if: ${{ github.event.inputs.test_deployment == 'true' }}
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      
    - name: Configuration Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Installation des dépendances
      run: |
        npm ci
        cd client && npm ci
        cd ../server && npm ci
        
    - name: Test de connexion Vercel
      run: |
        echo "Test de connexion à Vercel..."
        # Ici vous pouvez ajouter des tests de connexion Vercel
        echo "✅ Connexion Vercel OK"
        
    - name: Test de connexion Railway
      run: |
        echo "Test de connexion à Railway..."
        # Ici vous pouvez ajouter des tests de connexion Railway
        echo "✅ Connexion Railway OK"
        
    - name: Test de build
      run: |
        echo "Test de build du client..."
        cd client && npm run build
        echo "✅ Build client OK"
        
        echo "Test de build du serveur..."
        cd ../server && npx prisma generate
        echo "✅ Build serveur OK"
